### ISSUE TITLE
How to change the Forum Page layout?

### ISSUE THREAD

**Issue by PriscillaR** [chris-kent/Easy-Forums#4] opened 2016-08-29 06:56 UTC
![2016-08-29 08_54_09-tpsc gebruikersforum - tpsc gebruikersforum - confluence](https://cloud.githubusercontent.com/assets/21304020/18043145/4315b4fe-6dc6-11e6-8b79-2c1e08550b45.jpg)

We would like to move the "Search Forum" and the "Moderator" text line below the actual forum pages.
Also is it possible to remove the picture icons in the posts, so name only?

Thanks in advance.

**Comment by chris-kent** [comment] 2016-08-29 10:37
Hi there,

I can do something like that, make the home page more flexible and add some
configuration options.
Can you please send me through your Confluence SEN number so I can confirm
you are able to get support?

Thanks
Chris

**Comment by chris-kent** [comment] 2016-08-29 10:44
Hi Priscilla,

Never mind, I have found your SEN number.

What I can do are the following...  Let me know your thoughts...

1. Take out the Search and "moderators text" items from my built in macro.
I can create these as separate macros that you can place anywhere on the
page, so you can tailor the page to your liking.
2. For the Forum Summary macro I can add an option to show User Avatars.
This will be inherited by all the Forum pages in the space.

If this will suit your needs I will include the functionality in my next
plugin release.

Cheers
Chris

**Comment by PriscillaR** [comment] 2016-08-29 10:48
Hai Chris,

Both options are perfectly fine and a good improvement! It gives more options and flexibility.
So if you can adapt the macro and split it up in seperate macro's that would be perfect for us! 
I hope that release will come some!

Thank u for responding this quickly.

Regards,

Priscilla

**Comment by PriscillaR** [comment] 2016-09-05 14:46
Hi Chris,

Regarding to your optimalistion for Easy Forums, also the numbering of topics isn't going well. We have deleted a few test topics but the numbering goes forward, so, in the main page says there's 4 topics under the sub, but there's only 1. 

![image](https://cloud.githubusercontent.com/assets/21304020/18251231/3fc90036-7388-11e6-92ee-de060bf6228c.png)


Hope you know what i mean and that this is fixable.

Thank u.

Regards,

Priscilla

**Comment by chris-kent** [comment] 2016-09-06 12:28
Hi Priscilla,

I will look into this bug, it sounds weird because I don't store that
information, I count the children pages when the page loads.
I am restoring my system at the moment, after upgrading my PC, so I will be
addressing your issues soon.

Cheers
Chris

**Comment by chris-kent** [comment] 2016-09-07 10:47
Hi Priscilla.

I have tried to reproduce this scenario and I must say I do not get the
same results as you.

What I have tried...

1. Create a New topic.
2. Check the Forum home page and number of topics is correct (I have 2 now)
3. On the second topic I add comments
4. I now have 2 topics, one has no comments, the other has 2.
5. The numbers on the home page are correct (2 topics, 4 Posts)
6. I delete the last Topic ( which removes 1 topic and 3 posts)
7. Go back to Home page and the count is correct, 1 topic and 1 post.

So I would love to get to the bottom of this, can you please confirm a few
things...

1. What version of Confluence and my plugin do you have.
2. Can you provide steps on how you delete pages (I assume you use tools ->
delete)
3. Are you refreshing your browser to update status - silly question, I'm
sure you must be.
4. Can you please turn on logging for my plugin (net.kentcom -> ALL) in
admin -> logging and profiling.
5. You can send me logs, filter out everything other than lines marked with
net.kentcom if you like.

Thanks
Chris

**Comment by PriscillaR** [comment] 2016-09-12 09:14
Hi Chris,


1.      What version of Confluence and my plugin do you have.

Confluence is 5.10.1

Easy forums 2.5

2. Can you provide steps on how you delete pages (I assume you use tools ->
delete)

If I’m on the page I click on the three dots, click on delete and delete the page.

[cid:image007.png@01D20CE6.1E0E7100]

3.Are you refreshing your browser to update status - silly question, I'm
sure you must be.

Yes I refresh the page, of course I do. That’s the only way to see if it worked.

4. Can you please turn on logging for my plugin (net.kentcom -> ALL) in
admin -> logging and profiling.

Just turnt it on.

5. You can send me logs, filter out everything other than lines marked with
net.kentcom if you like.



SO here some screenshots so you can see what the problem is in our system:



Subforum

[cid:image008.png@01D20CE6.DFCE3410]


If I click on the post you see there’s only one topic while in the mainpage says there’s 3.
[cid:image009.png@01D20CE6.DFCE3410]
It’s really odd, and I really can’t find the problem, try to delete macro, create a new one…even that wont work.

Regards,

Priscilla Reeders
Servicedesk Engineer
--
[Logo The Patient Safety Company]

T:   +31 (0)72 - 8200 400    F:   +31 (0)72 - 8200 444
Comeniusstraat 5    1817 MS Alkmaar    The Netherlands
--
T:   +1 203 564 1453
One Stamford Plaza     263 Tresser Boulevard – 9th Floor, Stamford, CT 06901 USA
--
The Patient Safety Company<http://www.patientsafety.com/>     |     [Twitter icon] <http://www.twitter.com/TPSCompany>      [Facebook icon] <http://www.facebook.com/pages/The-Patient-Safety-Company/142373189191960>      [LinkedIn icon] <http://www.linkedin.com/company/the-patient-safety-company>      [Google Plus icon] <https://plus.google.com/109662848200118864184>      [YouTube icon] <http://www.youtube.com/user/TPSCompany>

Van: chris-kent [mailto:notifications@github.com]
Verzonden: woensdag 7 september 2016 12:47
Aan: chris-kent/Easy-Forums <Easy-Forums@noreply.github.com>
CC: Priscilla Reeders <priscilla@patientsafety.com>; Author <author@noreply.github.com>
Onderwerp: Re: [chris-kent/Easy-Forums] How to change the Forum Page layout? (#4)

Hi Priscilla.

I have tried to reproduce this scenario and I must say I do not get the
same results as you.

What I have tried...

1. Create a New topic.
2. Check the Forum home page and number of topics is correct (I have 2 now)
3. On the second topic I add comments
4. I now have 2 topics, one has no comments, the other has 2.
5. The numbers on the home page are correct (2 topics, 4 Posts)
6. I delete the last Topic ( which removes 1 topic and 3 posts)
7. Go back to Home page and the count is correct, 1 topic and 1 post.

So I would love to get to the bottom of this, can you please confirm a few
things...

1. What version of Confluence and my plugin do you have.
2. Can you provide steps on how you delete pages (I assume you use tools ->
delete)
3. Are you refreshing your browser to update status - silly question, I'm
sure you must be.
4. Can you please turn on logging for my plugin (net.kentcom -> ALL) in
admin -> logging and profiling.
5. You can send me logs, filter out everything other than lines marked with
net.kentcom if you like.

Thanks
Chris

**Comment by chris-kent** [comment] 2016-09-12 12:32
Hi Priscilla,

The images did not come through, you may need to add them in github so I can see them.

Cheers
Chris

**Comment by PriscillaR** [comment] 2016-09-12 12:37
Hi Chris,

here are the screenshots in the order I put them in the mail

![image](https://cloud.githubusercontent.com/assets/21304020/18435969/47f3999c-78f6-11e6-9571-3d419ec321d7.png)



![image](https://cloud.githubusercontent.com/assets/21304020/18435980/5d67c0be-78f6-11e6-9648-773048dd38c9.png)




![image](https://cloud.githubusercontent.com/assets/21304020/18435993/6eeb67b4-78f6-11e6-9771-da8039e6104c.png)

**Comment by chris-kent** [comment] 2016-09-13 06:34
Hi Priscilla,

I don't know why this is happening, but there is something in my code that
could allow this different behaviour.

The Create Forum and Create Topic buttons use my in-built templates. Pages
created from these templates add labels to the pages for my plugin to add
to the tables. So for every Topic that is created, the Confluence page
should have the label "easyforums-topic".  The Table will only show pages
with this label.  Unfortunately I don't think you will see the labels as I
hide them :(.  When you edit a page, you may be able to add labels and then
you should see what is already there. You may need to do this to verify
which pages are being shown in the tables.

What I did not do, is when I count the pages and provide a summary on the
Forum page, I don't use this label, I just count children pages and
comments. This could be the problem, but in a perfectly working system,
there should not be pages in the space without my labels on them - so I
thought anyway ;).

So, to verify this, from the tools menu, if you do a "View in Hierarchy",
you should be able to see all the pages in the space.  Now if you have more
pages in the space than shown in my tables, then this means pages exist
that have not been created using my Create buttons.  Or something else has
gone wrong.

Can you please expand the entire hierarchy, see what pages are in the space
and confirm if this could be the source of the discrepancy. I expect that
you will have some pages in the space without my plugin labels on them.  To
check this I think you will need to edit the pages as a described above.

If this is the case, I can resolve the discrepancy, but I would love to
know how these pages were generated....

Once you have done this, if you recognise the pages and can understand why
they are not shown (ie. missing the label), then maybe I can fix this bug
so this situation does not occur again.

I hope this makes sense :)

Thanks
Chris

**Comment by PriscillaR** [comment] 2016-09-13 06:57
Hi Chris,

I found the problem, it was indeed de childpages. I deleted the pages from de sub, But not in right way i found out, This is solved, nouw the rest;) I hope to see an update soon :) Thnx for the help!

**Comment by chris-kent** [comment] 2016-09-13 10:33
Hi Priscilla,

I don't quite understand what was wrong, but glad to know it is resolved.

I am currently working on an admin configuration page to implement your 2
new requests, so please look out for the next version soon.

Cheers
Chris

**Comment by chris-kent** [comment] 2016-09-21 11:25
Hi Priscilla,

I have uploaded a new version of Easy Forums (2.6) which has the feature
requests you asked for.  Please install this and provide any feedback or
improvements.

Cheers
Chris

**Comment by PriscillaR** [comment] 2016-09-22 13:06
Hi Chris,

Thanks for the notification, I will start with it on monday. Let you know how it goes!

Regards 

Priscillaw

**Closed** 2017-03-01 11:54 UTC
